[tool.poetry]
name = "frankencert"
version = "0.1.0"
description = "Continuation of the frankencert project with python-cryptography"
authors = ["Stefan Tatschner <stefan.tatschner@aisec.fraunhofer.de>"]
license = "Apache2"

[tool.poetry.dependencies]
python = "^3.10"
# aiohttp = "^3.8.0"
# argcomplete = "^2.0.0"
aiofiles = "^0.8.0"
aiosqlite = "^0.17.0"
cryptography = "^36.0.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
isort = "^5.10.1"
mypy = "^0.931"
pylsp-mypy = "^0.5.7"
pylsp-rope = "^0.1.8"
python-lsp-black = "^1.1.0"
python-lsp-server = "^1.3.3"
types-aiofiles = "^0.8.3"
types-cryptography = "^3.3.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
disallow_any_unimported = true
check_untyped_defs = true
ignore_missing_imports = true
allow_redefinition = true
warn_unreachable = true
disallow_untyped_calls = true
strict_equality = true
disallow_untyped_defs = true
warn_unused_ignores = true

[tool.black]
target-version = ['py310']

[tool.isort]
profile = "black"
