[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "frankencert"
version = "0.1.0"
description = "Continuation of the frankencert project with python-cryptography"
authors = ["Stefan Tatschner <stefan.tatschner@aisec.fraunhofer.de>"]
license = "Apache2"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
cryptography = "^36.0.1"
gallia = "1.1.0"
pyOpenSSL = "^22.0.0"
python-mbedtls = "^2.5.1"
types-pyOpenSSL = "^22.0.10"
pandas = "^1.5.0"
SQLAlchemy = "^1.4.41"
matplotlib = "^3.6.0"
pandas-stubs = "^1.5.0.220926"

[tool.poetry.scripts]
certrunner = "frankencert.runner:main"

[tool.poetry.group.dev.dependencies]
black = "^22.6.0"
flake8 = "^5.0.4"
isort = "^5.10.1"
mypy = "^0.971"
pylint = "2.14.5"
pylsp-mypy = "^0.6.2"
pyls-isort = "^0.2.2"
pylsp-rope = "^0.1.8"
pytest = "^7.1.2"
pytest-asyncio = "^0.19.0"
python-lsp-black = "^1.1.0"
python-lsp-server = "^1.5.0"
types-aiofiles = "^0.8.10"
myst-parser = "^0.18.0"
reuse = "^1.0.0"

[tool.mypy]
strict = true

[tool.black]
target-version = ['py310']

[tool.isort]
profile = "black"
