#!/usr/bin/python3

import subprocess
import sys
from enum import IntEnum


class State(IntEnum):
    WAITING = 0
    READING = 1


def main() -> None:
    buf = []
    start = "-----BEGIN CERTIFICATE-----\n"
    end = "-----END CERTIFICATE-----\n"
    state = State.WAITING
    for line in sys.stdin:
        if state == State.WAITING:
            if line == start:
                state = State.READING
                buf.append(line)
        elif state == State.READING:
            buf.append(line)
            if line == end:
                state = State.WAITING
                data = ''.join(buf).encode()
                buf = []
                cmd = ['openssl', 'x509', '-text', '-noout']
                subprocess.run(cmd, input=data)


if __name__ == '__main__':
    main()
